name: linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: x64
      - name: Install dependencies
        run: pip install pylint
      - name: Linter (pylint)
        run: pylint ./spacyfishing/*.py
