name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.8"
        architecture: x64
    - name: Install dependencies
    - run: | 
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Code quality (pylint)
    - run: pylint ./spacyfishing/*.py
    - name: run functional tests (pytest)
    - run: pytest ./tests
